sudo: true
language: bash
services:
  - docker
os:
  - linux
stages:
  - Build
jobs:
  include:
    - stage: Build
      script: 
        - sudo chmod -R 777 `pwd`
        - make -f Makefile-docker docker defconfig
        - make -f Makefile-docker docker all